version: '3.3'

services:

  nginx:
    build:
      ./nginx
    environment:
      - NGINX_USER=www-data
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - 8080:80
    links:
      - fpm

  fpm:
    build:
      ./fpm
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    links:
      - mysql

  composer:
    image: composer
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080